version: '3.8'

services:
  postgres-db:
    image: postgres:15-alpine
    container_name: library-db
    environment:
      POSTGRES_USER: alisher
      POSTGRES_PASSWORD: my_password
      POSTGRES_DB: library_oop
    ports:
      - "7000:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - library-net

  library-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: library-app
    stdin_open: true
    tty: true
    depends_on:
      - postgres-db
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/library_oop
    networks:
      - library-net

volumes:
  pgdata:

networks:
  library-net:
    driver: bridge